name: build windows

on:
  push:
    branches: [demo]
  pull_request:
    branches: [demo]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
        platform: [x64]
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'recursive'
      - uses: microsoft/setup-msbuild@main
      - shell: cmd
        run: |
          msbuild ./build-windows/demo-mediapipe.sln /p:Configuration=${{matrix.configuration}} /p:Platform=${{matrix.platform}}
